owner: wickepedia
repo: upptime

sites:
  - name: Wiki DE
    url: https://de.wickepedia.org
  - name: Wiki EN
    url: https://en.wickepedia.org
  - name: Wiki Apex
    url: https://wickepedia.org
  
status-website:
  cname: status.wickepedia.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wickepedia Status
