owner: wickepedia
repo: upptime

sites:
  - name: Wiki DE
    url: https://de.wickepedia.org
  - name: Wiki EN
    url: https://en.wickepedia.org
  - name: Wiki Apex
    url: https://wickepedia.org
  - name: Short URL
    url: https://wickepedia.org/r/3
  - name: REST API
    url: https://de.wickepedia.org/rest.php/v1/page/Main_Page
    method: GET
  - name: Parsoid
    url: https://de.wickepedia.org/api.php?action=visualeditor&format=json&paction=parse&page=Main_Page
    method: GET
    __dangerous__body_down: "apierror-"
    
workflowSchedule:
  responseTime: "0 * * * *"
  graphs: "2 * * * *"
  
status-website:
  cname: status.wickepedia.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wickepedia Status
  navbar:
    - title: Wiki
      href: https://wickepedia.org
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/
